using UnityEngine;

/// <summary>
/// 
///  This class is responsible for random spawning of falling letter
///  objects. This class is used by MainMenu and MainGame scenes.
/// 
///  This class contains AI generated content
/// 
/// </summary>
public class HandleSpawning : MonoBehaviour
{
    [SerializeField] private GameObject _key;
    [SerializeField] private Transform[] _spawnPositions;
    [SerializeField] private float _startTime=2.5f;
    private float _timeBetweenSpawn;

    /// <summary>
    /// 
    ///  Creates a time gap in between each spawns.
    /// 
    /// </summary>
    private void Start()
    {
        _timeBetweenSpawn = _startTime;
        
    }


    /// <summary>
    /// 
    ///  Spawning a new falling letter object every time the timer reaches 0.
    /// 
    /// </summary>
    private void Update()
    {
        if(_timeBetweenSpawn <=0)
        {
            Spawn();
            _timeBetweenSpawn =_startTime;
        }
        else{
            _timeBetweenSpawn -=Time.deltaTime;
        }
        
    }

    /// <summary>
    /// 
    ///  Responsible for spawning falling letter objects in random pre-assigned
    ///  locations.
    /// 
    ///  This function is generated by the LLM ChatGPT (GPT-4) by OpenAI.
    /// 
    /// </summary>
    private void Spawn()
    {
        int SpawnPosition = Random.Range(0,_spawnPositions.Length);
        Instantiate(_key,_spawnPositions[SpawnPosition].position,Quaternion.identity);
    }
}
