using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// 
///  Used to perform input validation during login request initiation.
/// 
///  This class contains AI generated content.
/// 
/// </summary>
public class HandleLoginValidate : MonoBehaviour
{
    [SerializeField] private TMP_InputField _emailInputField;
    [SerializeField] private TMP_InputField _passwordInputField;
    [SerializeField] private TMP_Text _warningTextEmail;
    [SerializeField] private TMP_Text _warningTextPassword;
    [SerializeField] private Button _loginButton;

    /// <summary>
    /// 
    ///  Disables the login button upon start.
    ///  Attaches onValueChanged event to the input fields to continuously validate the input.
    /// 
    ///  This function is generated by the LLM ChatGPT (GPT-4) by OpenAI.
    /// 
    /// </summary>
    private void Start()
    {
        _loginButton.interactable = false;
        _emailInputField.onValueChanged.AddListener(ValidateForm);
        _passwordInputField.onValueChanged.AddListener(ValidateForm);
    }

    /// <summary>
    /// 
    ///  Performs input validation by accessing functions of the InputValidator.
    /// 
    ///  This function is generated by the LLM ChatGPT (GPT-4) by OpenAI.
    /// 
    /// </summary>
    /// 
    /// <param name="_"> Ignored parameter. User because onValueChanged listener demands it. </param>
    private void ValidateForm(string _)
    {
        string email = _emailInputField.text;
        string password = _passwordInputField.text;

        if (InputValidator.IsFieldEmpty(email, _warningTextEmail, "Email")) return;
        if (!InputValidator.IsValidEmail(email, _warningTextEmail)) return;
        if (InputValidator.IsFieldEmpty(password, _warningTextPassword, "Password")) return;
        if (!InputValidator.IsPasswordValid(password, _warningTextPassword)) return;

        _loginButton.interactable = true;
    }
}
