using UnityEngine;
using TMPro;

/// <summary>
/// 
///  This class is used to destroy the falling letter objects once they 
///  reach a specific point out of the screen. This class is attached to 
///  all falling letter objects in the Main Menu.
/// 
///  This class contains AI generated content
/// 
/// </summary>
public class HandleDestroyComponent : MonoBehaviour
{
    [SerializeField] private float _destroyPoint;

    /// <summary>
    /// 
    ///  Destroys the falling letter when it reaches a certain point
    ///  to reduce the amount of resources used.
    /// 
    ///  This function is generated by the LLM ChatGPT (GPT-4) by OpenAI.
    /// 
    /// </summary>
    private void Update()
    {
        if(transform.position.y <= _destroyPoint)
        {
            Destroy(this.gameObject);
        }
    }
}
